### ISSUE TITLE
Footer doesn't stick to bottom of the page if there isn't enough content

### ISSUE THREAD

**Issue by redrubycorn** [redrubycorn/11ty-playground#1]
If the content doesn't fill out the whole viewport height, the footer is not at the bottom of the page which doesn't look good.

* If there is not enough content, the footer should stick to the bottom
* Otherwise it should just be at the end of the page (need to scroll down to see it)
![image](https://github.com/redrubycorn/11ty-playground/assets/91390779/02740075-ac28-4f72-84c5-d2b73ce4cdd3)

**Comment by arbiasgjoshi** [comment]
Could you assign this one to me? I'd like to work on it?

**Comment by redrubycorn** [comment]
Hi, sure but I am totally new to GitHub Issues and that stuff. This is a 11ty project to build some sort of starter that I can use for future projects :-) 
I assigned it to you but I don't know if I need to do anything else?

**Comment by redrubycorn** [comment]
Hi,

thanks, looks good to me :-)
